name: Headers update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # Runs every Sunday at midnight UTC

permissions:
  contents: write  # Grants write access to push changes
  pull-requests: write # and create PRs

jobs:
  run-bash-and-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # to figure out last change to the json file

      - uses: fregante/setup-git-user@v2
      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Check for new headers on IANA.ORG
        run: pnpm tsx tools/headers.ts

      - name: Check for changes
        id: git-state
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Create branch, commit, and push changes
        id: create-branch
        if: steps.git-state.outputs.changes == 'true'
        run: |
          BRANCH_NAME="headers-update-$(date +%Y%m%d)"
          echo "branch-name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Create a pull request
        if: steps.git-state.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          base: master
          branch: ${{ steps.create-branch.outputs.branch-name }}
          commit-message: "Changed well-known headers"
          title: "Well-known headers update"
          body: "This PR contains automated updates generated by the weekly workflow."
          delete-branch: false
